package com.xelerate.customer01.be.ent.becustomer.customerdetails;

import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;
import com.xelerate.core.XException;
import com.xelerate.be.contracts.InitEntityNodeIface;
import com.xelerate.customer01.be.attr.BaAddrEntInit;
import com.xelerate.be.contracts.Element;

public class AddressesEntInit extends BaAddrEntInit implements InitEntityNodeIface {
  public void initialize(AddressesEnt BEData) throws XException {
    // Call Super Method...
    super.initialize(BEData);
    // For addrLn1...
    BEData.addrLn1Elm = new Element("addrLn1", "SYS_X3_13");
    // For addrLn2...
    BEData.addrLn2Elm = new Element("addrLn2", "SYS_X3_14");
    // For addrLn3...
    BEData.addrLn3Elm = new Element("addrLn3", "SYS_X3_15");
    // For city...
    BEData.cityElm = new Element("city", "SYS_X3_16");
    // For state...
    BEData.stateElm = new Element("state", "SYS_X3_17");
    // For country...
    BEData.countryElm = new Element("country", "SYS_X3_18");
    // For zipCode...
    BEData.zipCodeElm = new Element("zipCode", "SYS_X3_19");
    // For addrType...
    BEData.addrTypeElm = new Element("addrType", "pcShortCode");
  } // End Validate Function...
}
